version: '3.8'

services:
  backend:
    build: .
    container_name: ecommerce-backend
    restart: always
    env_file:
      - .env.dev  # or .env.prod
    ports:
      - '3000:3000'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge